---
title: "COVID-19 Summary-Based Analysis Pilot Study"
author : "고영현 (2014-19984)"
date: '2020-07-01'
output :
  html_document:
    theme: journal
---

<br>
<br>


```{r setup, echo = FALSE}
## Library
library(knitr)
library(tidyverse)
library(readxl)
library(GGally)

setwd("C:\\Users\\1234\\Desktop\\고영현\\수업\\인턴십\\변수 데이터")
```


<br>
<br>

### 1. Data Preprocessing

<br>

#### 1.1. Merging Variables

```{r}

data_yh <- read.csv("data_고영현.csv", header = TRUE)

data_de <- read.csv("data_doeun.csv", header = TRUE) %>%
  rename(Country = country,
         a_Log = logi_a, b_Log = logi_b, c_Log = logi_c,
         a_Ber = bert_a, b_Ber = bert_b, c_Ber = bert_c,
         a_Gom = gomp_a, b_Gom = gomp_b, c_Gom = gomp_c) %>%
  select(-(2:11))

data_kh <- read.csv("data_kh.csv", header = TRUE) %>%
  select(-1, -(3:12))

data_hy <- read.csv("data_김학용.csv", header = TRUE) %>%
  rename(Country = country2) %>%
  select(-1, -(3:13))


## left join by country
data <- data_yh %>%
  left_join(data_de, by = "Country") %>%
  left_join(data_kh, by = "Country") %>%
  left_join(data_hy, by = "Country")
  
```

<br>

#### 1.2. Standardizing the data

```{r}

#head(data); str(data) 

mean_data <- apply(data[, 13:38], 2, mean, na.rm = TRUE)
sd_data <- apply(data[, 13:38], 2, sd, na.rm = TRUE)

st_data <- c()
for (i in 1:length(mean_data)){
  st_data[i] <- (data[i +12] - mean_data[i]) / sd_data[i]
}
st_data <- data.frame(st_data)
names(st_data) <- names(data[, 13:38])

st_data <- cbind(data[, 1:12], st_data)


write.csv(st_data, "standardized_data.csv")

```

<br>
<br>

### 2. 변수 방향성 check 및 해석

<br>

#### 2.1. 독립변수 SLR
```{r, eval = FALSE}

# GDP 대비 저축률
summary(lm(data$a_Log ~ data$saving_rate))
summary(lm(data$b_Log ~ data$saving_rate))
summary(lm(data$c_Log ~ data$saving_rate))

summary(lm(data$a_Ber ~ data$saving_rate))
summary(lm(data$b_Ber ~ data$saving_rate))
summary(lm(data$c_Ber ~ data$saving_rate))

summary(lm(data$a_Gom ~ data$saving_rate))
summary(lm(data$b_Gom ~ data$saving_rate))
summary(lm(data$c_Gom ~ data$saving_rate))


# 유아접종률
summary(lm(data$a_Log ~ data$child_vaccination))
summary(lm(data$b_Log ~ data$child_vaccination))
summary(lm(data$c_Log ~ data$child_vaccination))

summary(lm(data$a_Ber ~ data$child_vaccination))
summary(lm(data$b_Ber ~ data$child_vaccination))
summary(lm(data$c_Ber ~ data$child_vaccination))

summary(lm(data$a_Gom ~ data$child_vaccination))
summary(lm(data$b_Gom ~ data$child_vaccination))
summary(lm(data$c_Gom ~ data$child_vaccination))


# 국민총소득
summary(lm(data$a_Log ~ data$GNI))
summary(lm(data$b_Log ~ data$GNI))
summary(lm(data$c_Log ~ data$GNI))

summary(lm(data$a_Ber ~ data$GNI))
summary(lm(data$b_Ber ~ data$GNI))
summary(lm(data$c_Ber ~ data$GNI))

summary(lm(data$a_Gom ~ data$GNI))
summary(lm(data$b_Gom ~ data$GNI))
summary(lm(data$c_Gom ~ data$GNI))


# 인간개발지수
summary(lm(data$a_Log ~ data$HDI))
summary(lm(data$b_Log ~ data$HDI))
summary(lm(data$c_Log ~ data$HDI))

summary(lm(data$a_Ber ~ data$HDI))
summary(lm(data$b_Ber ~ data$HDI))
summary(lm(data$c_Ber ~ data$HDI))

summary(lm(data$a_Gom ~ data$HDI))
summary(lm(data$b_Gom ~ data$HDI))
summary(lm(data$c_Gom ~ data$HDI))


# 기대수명
summary(lm(data$a_Log ~ data$life_expectancy))
summary(lm(data$b_Log ~ data$life_expectancy))
summary(lm(data$c_Log ~ data$life_expectancy))

summary(lm(data$a_Ber ~ data$life_expectancy))
summary(lm(data$b_Ber ~ data$life_expectancy))
summary(lm(data$c_Ber ~ data$life_expectancy))

summary(lm(data$a_Gom ~ data$life_expectancy))
summary(lm(data$b_Gom ~ data$life_expectancy))
summary(lm(data$c_Gom ~ data$life_expectancy))


# 영양실조인구비율
summary(lm(data$a_Log ~ data$malnutrition))
summary(lm(data$b_Log ~ data$malnutrition))
summary(lm(data$c_Log ~ data$malnutrition))

summary(lm(data$a_Ber ~ data$malnutrition))
summary(lm(data$b_Ber ~ data$malnutrition))
summary(lm(data$c_Ber ~ data$malnutrition))

summary(lm(data$a_Gom ~ data$malnutrition))
summary(lm(data$b_Gom ~ data$malnutrition))
summary(lm(data$c_Gom ~ data$malnutrition))


# 인구밀도
summary(lm(data$a_Log ~ data$pop_density))
summary(lm(data$b_Log ~ data$pop_density))
summary(lm(data$c_Log ~ data$pop_density))

summary(lm(data$a_Ber ~ data$pop_density))
summary(lm(data$b_Ber ~ data$pop_density))
summary(lm(data$c_Ber ~ data$pop_density))

summary(lm(data$a_Gom ~ data$pop_density))
summary(lm(data$b_Gom ~ data$pop_density))
summary(lm(data$c_Gom ~ data$pop_density))


# 순이동률
summary(lm(data$a_Log ~ data$moving_rate))
summary(lm(data$b_Log ~ data$moving_rate))
summary(lm(data$c_Log ~ data$moving_rate))

summary(lm(data$a_Ber ~ data$moving_rate))
summary(lm(data$b_Ber ~ data$moving_rate))
summary(lm(data$c_Ber ~ data$moving_rate))

summary(lm(data$a_Gom ~ data$moving_rate))
summary(lm(data$b_Gom ~ data$moving_rate))
summary(lm(data$c_Gom ~ data$moving_rate))


# 도시화율
summary(lm(data$a_Log ~ data$urbanization))
summary(lm(data$b_Log ~ data$urbanization))
summary(lm(data$c_Log ~ data$urbanization))

summary(lm(data$a_Ber ~ data$urbanization))
summary(lm(data$b_Ber ~ data$urbanization))
summary(lm(data$c_Ber ~ data$urbanization))

summary(lm(data$a_Gom ~ data$urbanization))
summary(lm(data$b_Gom ~ data$urbanization))
summary(lm(data$c_Gom ~ data$urbanization))

```

<br>